apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod-with-binpack-scheduler-2
  namespace: test-binpack-scheduler
spec:
  containers:
  - name: gpu-container-with-binpack-scheduler-2
    # image: nvidia/cuda:12.6-runtime
    image: nvidia/cuda:12.6.3-cudnn-devel-ubuntu22.04
    command:
      - "/bin/sh"
      - "-c"
    args:
      - nvidia-smi && tail -f /dev/null
    resources:
      requests:
        nvidia.com/gpu: 1
      limits:
        nvidia.com/gpu: 1
  tolerations:
  - key: nvidia.com/gpu
    operator: Exists
    effect: NoSchedule
  schedulerName: gpu-binpack-scheduler